#! /bin/env bash

set -e

# Variables
storePath=~/Documents/Config-Files

# Home directory
cd ~
cp .bashrc $storePath
cp .vimrc $storePath

## swaywm
#cd ~/.config/sway
#cp config $storePath/config.sway

## waybar
#cd ~/.config/waybar
#cp config $storePath/config.waybar
#cp style.css $storePath/style.css.waybar

# alacritty
cd ~/.config/alacritty
cp alacritty.toml $storePath

# i3 configs
cd ~/.config/i3/
cp config $storePath
cp picom.conf $storePath
cp i3status.conf $storePath
